### ISSUE TITLE
UnquotedServicePath.md

### ISSUE THREAD

**Issue by itclientmanagement** [nickvourd/Windows-Local-Privilege-Escalation-Cookbook#6]
Hi Nickvourd,
I'm Ethan and i'm trying to run your troubleshooting to install the UnquotedServicePath.md --> https://github.com/nickvourd/Windows-Local-Privilege-Escalation-Cookbook/blob/master/Notes/UnquotedServicePath.md

but when i want to START the service i got this message:

<img width="627" alt="2024-10-25_10h35_25" src="https://github.com/user-attachments/assets/81e13a4b-d47d-4399-8807-c2a201103055">

any idea why?
Thanks for your support on this topic.

**Comment by nickvourd** [comment]
Hello man, Sorry for the delay. I need to check this.

**Comment by nickvourd** [comment]
Hello I think the reason that you are using Windows 11, try to use it on Windows 10
